spring:
  mail:
    host: smtp.gmail.com
    username: [email]
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: [password-email]
  datasource:
    password: [password]
    username: [username]
    url: jdbc:postgresql://localhost:5432/ms-email
  jpa:
    hibernate:
      ddl-auto: update
#  rabbitmq:
#    queue: ms.email
#    addresses: amqps://[url]
server:
  port: '8080'
